// The actual bindings are generated by build.rs and placed in OUT_DIR
// to avoid race conditions during parallel builds with different features

#![allow(dead_code)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]
#![allow(improper_ctypes)]
#![allow(deref_nullptr)]
#![allow(clippy::unreadable_literal)]
#![allow(unpredictable_function_pointer_comparisons)]

include!(concat!(env!("OUT_DIR"), "/plugin_h.rs"));
