[package]
name = "example_plugin_rs"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oden_plugin_rs = { path = "../../oden_plugin_rs", features = [
    "glam_conversion",
] }
image = { version = "0.25", default-features = false, features = ["png"] }

[workspace]
members = []
